# Generated by Django 4.0 on 2021-12-29 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irgan', models.CharField(max_length=122)),
                ('oiur', models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 20, 2, 52, 47008, tzinfo=utc)),
        ),
    ]
