# Generated by Django 4.0 on 2021-12-29 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_testmodelim_alter_story_expiration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModelim',
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 20, 4, 13, 203692, tzinfo=utc)),
        ),
    ]
