# Generated by Django 4.0 on 2021-12-30 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_delete_testmodelim_alter_story_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='like',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 31, 10, 4, 41, 453073, tzinfo=utc)),
        ),
    ]
