# Generated by Django 4.0 on 2021-12-30 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_remove_rating_dislike_remove_rating_like_rating_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='active',
        ),
        migrations.AddField(
            model_name='story',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 31, 14, 2, 45, 246706, tzinfo=utc)),
        ),
    ]
