# Generated by Django 4.0 on 2021-12-30 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_remove_story_active_story_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 31, 16, 58, 17, 737204, tzinfo=utc)),
        ),
    ]
