# Generated by Django 4.0 on 2021-12-31 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_story_content_alter_story_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 16, 32, 26, 683187, tzinfo=utc)),
        ),
    ]
