# Generated by Django 4.0 on 2022-01-01 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_draft_alter_story_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='additional',
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 14, 49, 42, 3760, tzinfo=utc)),
        ),
    ]
