# Generated by Django 4.0 on 2022-01-01 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_story_expiration_storycomment_commentrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycomment',
            name='completed',
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 14, 58, 46, 752338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 14, 58, 46, 752887, tzinfo=utc)),
        ),
    ]
