# Generated by Django 4.0 on 2022-01-02 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_remove_storycomment_completed_alter_story_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='story.storycomment'),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 15, 46, 53, 701419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 15, 46, 53, 701964, tzinfo=utc)),
        ),
    ]
