# Generated by Django 4.0 on 2022-01-04 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_alter_story_expiration_alter_storycomment_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 18, 25, 33, 789089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 18, 25, 33, 789893, tzinfo=utc)),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['draft', 'completed'], name='story_story_draft_9138f2_idx'),
        ),
    ]
