# Generated by Django 4.0 on 2022-01-04 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_remove_story_story_story_draft_9138f2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 20, 38, 5, 812606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 20, 38, 5, 813384, tzinfo=utc)),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['draft', 'completed'], name='story_story_draft_9138f2_idx'),
        ),
    ]
