# Generated by Django 4.0.1 on 2022-01-09 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_alter_story_completed_alter_story_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 20, 29, 53, 119603, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 20, 29, 53, 120219, tzinfo=utc)),
        ),
    ]
