# Generated by Django 4.0.1 on 2022-01-10 11:59

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_remove_rating_rate_alter_story_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 11, 59, 27, 816571, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 11, 59, 27, 817317, tzinfo=utc)),
        ),
    ]
