# Generated by Django 4.0.1 on 2022-01-10 12:00

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_remove_commentrating_rate_alter_story_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrating',
            name='rate',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 12, 0, 57, 142100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 12, 0, 57, 142836, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='commentrating',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='comment rating validation'),
        ),
    ]
