# Generated by Django 4.0.1 on 2022-01-10 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0022_commentrating_rate_alter_story_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 13, 11, 3, 323874, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 13, 11, 3, 324487, tzinfo=utc)),
        ),
    ]
