# Generated by Django 4.0.1 on 2022-01-10 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0023_alter_story_expiration_alter_storycomment_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 13, 11, 56, 273926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 13, 11, 56, 274538, tzinfo=utc)),
        ),
    ]
