# Generated by Django 4.0.1 on 2022-01-10 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0024_alter_story_expiration_alter_storycomment_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 40, 9, 162945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 40, 9, 163577, tzinfo=utc)),
        ),
    ]
