# Generated by Django 4.0.1 on 2022-01-15 15:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0025_alter_story_expiration_alter_storycomment_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycomment',
            name='attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 40, 33, 156871, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 1, 15, 15, 40, 33, 156879, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2022, 1, 16, 15, 40, 33, 156883, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 40, 33, 157505, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='StoryAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='story.story')),
            ],
        ),
    ]
