# Generated by Django 4.0.1 on 2022-01-15 15:40

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0026_storycomment_attachment_alter_story_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 40, 59, 508380, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 1, 15, 15, 40, 59, 508390, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2022, 1, 16, 15, 40, 59, 508396, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 40, 59, 509190, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='StoryAttach',
        ),
    ]
