# Generated by Django 4.0.1 on 2022-01-17 14:04

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0027_alter_story_expiration_alter_storycomment_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='add_celery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 14, 4, 4, 890182, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 1, 17, 14, 4, 4, 890191, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2022, 1, 18, 14, 4, 4, 890195, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 14, 4, 4, 890820, tzinfo=utc)),
        ),
    ]
